version: '3'

services:
  api:
    build:
      context: ./api
    ports:
      - "6000:6000"
    volumes:
      - ./api:/app
    depends_on:
      - etl

  etl:
    build:
      context: ./etl
    volumes:
      - ./etl:/app


